#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision: 8595 $
# $Date: 2010-07-12 10:02:16 -0400 (lun 12 jui 2010) $

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG="pf-asterisk-prompts-xivo"
DEB_TB_DEPS=""

default:

