#!/bin/sh
# $Revision$
# $Date$
#
### BEGIN INIT INFO
# Provides:          pf-xivo-agid
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:      asterisk
# Should-Stop:       asterisk
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup daemon script for XIVO AGID
### END INIT INFO
#
set -e

DAEMONNAME=fakesvc
DAEMON=/tmp/fakesvc.py
PIDFILE=/var/run/$DAEMONNAME.pid

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

case "$1" in
  start)
    log_daemon_msg "Starting FAKESVC" "$DAEMONNAME"
    echo "STARTING fakesvc" >> /var/log/fakesvc
    if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON 2>&1 >> /var/log/fakesvc;
    then
        echo "OK"  >> /var/log/fakesvc
        log_end_msg 0
    else
        echo "KO"  >> /var/log/fakesvc
        log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping FAKESVC" "$DAEMONNAME"
    echo "STOPPING fakesvc" >> /var/log/fakesvc
    if start-stop-daemon --stop --quiet --oknodo --retry 5 --pidfile $PIDFILE;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON "FAKESVC" || status="$?"
    echo "STATUS fakesvc - $status" >> /var/log/fakesvc
    status_of_proc -p $PIDFILE $DAEMON "FAKESVC" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
