<?php

#
# XiVO Web-Interface
# Copyright (C) 2020  Proformatique <technique@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

$array['element'] = array();

$array['element']['proxy_ip'] = array();
$array['element']['proxy_ip']['default'] = '';

$array['element']['proxy_port'] = array();
$array['element']['proxy_port']['default'] = '';

$array['element']['backup_proxy_ip'] = array();
$array['element']['backup_proxy_ip']['default'] = '';

$array['element']['backup_proxy_port'] = array();
$array['element']['backup_proxy_port']['default'] = '';

$array['element']['registrar_ip'] = array();
$array['element']['registrar_ip']['default'] = '';

$array['element']['registrar_port'] = array();
$array['element']['registrar_port']['default'] = '';

$array['element']['backup_registrar_ip'] = array();
$array['element']['backup_registrar_ip']['default'] = '';

$array['element']['backup_registrar_port'] = array();
$array['element']['backup_registrar_port']['default'] = '';

$array['element']['outbound_proxy_ip'] = array();
$array['element']['outbound_proxy_ip']['default'] = '';

$array['element']['outbound_proxy_port'] = array();
$array['element']['outbound_proxy_port']['default'] = '';

$array['element']['username'] = array();
$array['element']['username']['default'] = '';

$array['element']['auth_username'] = array();
$array['element']['auth_username']['default'] = '';

$array['element']['password'] = array();
$array['element']['password']['default'] = '';

$array['element']['display_name'] = array();
$array['element']['display_name']['default'] = '';

$array['element']['number'] = array();
$array['element']['number']['default'] = '';

$array['element']['dtmf_mode'] = array();
$array['element']['dtmf_mode']['default'] = '';

$array['element']['voicemail'] = array();
$array['element']['voicemail']['default'] = '';

?>