#!/bin/sh

. ./sources.pkg

VER=$(cat SOURCE-VERSION)

echo "Preparing source for ${PKG_NAME}_${VER}"

if [ -n "${DFSG_EXCLUDE_PATTERNS}" ]; then
	FILENAME="${PKG_NAME}_${VER}+dfsg.orig.tar.gz"
else
	FILENAME="${PKG_NAME}_${VER}.orig.tar.gz"
fi

if [ ! -e ${DEST_PATH}/${FILENAME} ]; then
	echo "The corresponding tarball is missing (${FILENAME})" >&2
	exit 1
fi

rm -rf tmp
mkdir tmp
tar xz -C tmp -f ${DEST_PATH}/${FILENAME}

cd tmp/${PKG_NAME}-${VER}
ln -s ../../patches patches
quilt push -a
if [ $? -eq 0 ]; then
    pwd
    quilt pop -a
    for patches in $(quilt unapplied); do
        quilt push && quilt refresh
    done
fi

echo "Done !"

