#!/bin/bash

. /usr/sbin/pf-common-read-config

MONIT_CHECKS=/usr/share/pf-xivo-monitoring/checks
MONIT_CONF_DIR=/etc/monit/conf.d

is_installed()
{
  package=$1
  dpkg -l $package >/dev/null 2>/dev/null;
}

activate_check()
{
  check=$1

  if [ ! -L $MONIT_CONF_DIR/$check ]; then
    rm $MONIT_CONF_DIR/$check
  fi

  if [ ! -e $MONIT_CONF_DIR/$check ]; then
    ln -s $MONIT_CHECKS/$check $MONIT_CONF_DIR/$check
  fi
}

deactivate_check()
{
  check=$1
  rm -f $MONIT_CONF_DIR/$check
}

activate_if_installed()
{
  package=$1

  if is_installed $package; then
    activate_check $package
  else
    deactivate_check $package
  fi
}

# commun sys checks
activate_check base-system

# known services
for check in $MONIT_CHECKS/*; do
  service=$(basename $check)
  if [ "$service" != "isc-dhcp-server" ]; then
    # isc-dhcp will be updated by sysconfd
    activate_if_installed $service
  fi
done

# Server config
# (backup old file)
if [ -e /etc/monit/monitrc ]; then
  today=$(date +%Y%m%d%H%M%S)
  cp /etc/monit/monitrc /etc/monit/monitrc.$today
fi
sed "s/#PRODUCT#/${PRODUCT}/g" /etc/monit/monitrc.tmpl > /etc/monit/monitrc

emails=$(get_full_email_alerts "monit")
if [ -n "$emails" ]; then
  for email in $emails; do
    echo "set alert $email but not on { instance changed }" >> /etc/monit/monitrc
  done
fi

# restart service to take changes into account
invoke-rc.d monit restart >/dev/null

