#!/bin/bash

. /usr/sbin/pf-common-read-config

MONIT_CHECKS=/usr/share/pf-xivo-monitoring/checks
MONIT_CONF_DIR=/etc/monit/conf.d

is_installed()
{
  PKG=$1
  dpkg -l ${PKG} >/dev/null 2>/dev/null;
}

activate_check()
{
  PL=$1

  if [ ! -e ${MONIT_CONF_DIR}/${PL} ]; then
    ln -s ${MONIT_CHECKS}/${PL} ${MONIT_CONF_DIR}/${PL}
  fi
}

deactivate_check()
{
  PL=$1
  rm -f ${MONIT_CONF_DIR}/${PL}
}

activate_if_installed()
{
  PKG=$1

  if is_installed ${PKG}; then
    ACT=activate_check
  else
    ACT=deactivate_check
  fi

  ${ACT} ${PKG}
}

# commun sys checks
activate_check base-system

# known services
for CHECK in ${MONIT_CHECKS}/*; do
  SRV=$(basename ${CHECK})
  if [ "${SRV}" != "isc-dhcp-server" ]; then
    activate_if_installed ${SRV}
  fi
done

# Server config
# (backup old file)
if [ -e /etc/monit/monitrc ]; then
  DATE=$(date +%Y%m%d%H%M%S)
  cp /etc/monit/monitrc /etc/monit/monitrc.${DATE}
fi
sed "s/#PRODUCT#/${PRODUCT}/g" /etc/monit/monitrc.tmpl >/etc/monit/monitrc

EMAILS=$(get_full_email_alerts "monit")
if [ -n "${EMAILS}" ]; then
  for EM in ${EMAILS}; do
    echo "set alert ${EM} but not on { instance changed }" >>/etc/monit/monitrc
  done
fi

# restart service to take changes into account
invoke-rc.d monit restart >/dev/null

