#!/bin/bash
# This script is used to keep up to date xivo-sounds directories, used only for
# digium and greenable.
#   * get source tarballs
#   * extract tarballs, correct rights is needed
#   * create tarball with all datas
#   * add tarball in vcs

. ./sources.pkg

vcs_add () {
    tarball_name=$1
    # TODO add git support
    echo "keep vcs up-to-date"
    svn add $tarball_name
}

clean_tmp_dir () {
    # clean tmp_dir
    if [ -d $tmp_dir ]; then
        rm -rf $tmp_dir
    fi
}

prepare_temp_dir () {
    tmp_dir=$1
    echo "Prepare build directory $tmp_dir"
    clean_tmp_dir
    mkdir -p $tmp_dir/tarballs
    rsync -av asterisk xivo freeswitch $tmp_dir/ --exclude='.svn' > /dev/null 2>&1
}

get_tarball () {
    filename=$1
    tarball_url=$2
    tarball_dest=$3

    if [ ! -f $tarball_dest ]; then
        echo "Get tarball $filename"
        wget -nv -T10 -t3 -O $tarball_dest $tarball_url > /dev/null 2>&1
    fi
}

extract_digium_data () {
    tarball=$1
    language=$2

    case $language in
        "en") dest_dir="en_US";;
        "es") dest_dir="es_ES";;
        "fr") dest_dir="fr_CA";;
        *) echo "Error this language is not used"; exit 1;;
    esac
    tarball_path="$tmp_dir/asterisk/wav/$dest_dir"

    echo "extract $tarball on $tarball_path"
    tar -xvzf $tarball -C $tarball_path > /dev/null 2>&1
    # overriden by pf-asterisk-prompts-xivo
    if [ $language = "fr" ]; then
        find $tarball_path -name "conf-adminmenu.wav" -delete
    fi
    echo "asterisk/war/$dest_dir is up-to-date"
}

prepare_greenable_tarball () {
    # Prepare Greenable sounds archives

    # get tarball
    tarball_url="$greenable_url/$greenable_filename"
    greenable_tarball="$tmp_tarballs_path/$greenable_filename"
    greenable_dest="$tmp_dir/asterisk/gsm/de_DE"
    wget -nv -T10 -t3 -O $greenable_tarball $tarball_url > /dev/null 2>&1

    # Extract and correct rights
    echo "extract $greenable_filename on $tmp_tarballs_path"
    tar xvzf $greenable_tarball -C $tmp_tarballs_path > /dev/null 2>&1
    temp_dir="$tmp_tarballs_path/de" 
    if [ -d $temp_dir ]; then
        chmod 755 $temp_dir
        find $temp_dir -type d -exec chmod 755 {} \;
        find $temp_dir -type f -exec chmod 644 {} \;
    fi

    # Synchronize data
    rsync -av $temp_dir/ $greenable_dest/ > /dev/null 2>&1
    echo "$greenable_dest is up-to-date"
}

create_final_tarball () {
    tmp_dir=$1
    tarball_name="pf-xivo-sounds_${xivo_sounds_version}.orig.tar.gz"

    echo "Create tarball $tarball_name"
    cd $tmp_dir
    tar cvzf ../tarballs/$tarball_name asterisk freeswitch xivo > /dev/null 2>&1
    cd ..
    if [ $? -eq 0 ]; then
        clean_tmp_dir
        vcs_add tarballs/$tarball_name
    else
        echo "impossible to build tarballs/$tarball_name"
        exit -1
    fi
}


xivo_sounds_version=$(cat ./SOURCE-VERSION)

tmp_dir='tmp'

prepare_temp_dir $tmp_dir

# Prepare Digium sounds archive
for language in $ast_languages; do
    tmp_tarballs_path="$tmp_dir/tarballs"
    filename="${ast_tarball_prefix}-${language}-wav-${ast_version}.tar.gz"
    tarball_url="$ast_base_url/$filename"
    tarball="$tmp_tarballs_path/$filename"
    get_tarball $filename $tarball_url $tarball
    extract_digium_data $tarball $language
done

# Prepare Greenable sounds archive
prepare_greenable_tarball

create_final_tarball $tmp_dir
