#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision: 4047 $
# $Date: 2008-09-12 02:53:09 +0200 (Fri, 12 Sep 2008) $

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG="pf-xivo-cti-server"
DEB_TB_DEPS=""
DEB_TAR_EXTRA_OPTIONS="--exclude=*.pyc"

default:
