#!/usr/bin/python
# vim: set fileencoding=utf-8 :

# Copyright (C) 2007-2011  Avencall
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Alternatively, XiVO CTI Server is available under other licenses directly
# contracted with Pro-formatique SARL. See the LICENSE file at top of the
# source tree or delivered in the installable package in which XiVO CTI Server
# is distributed for more details.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

__author__ = 'Corentin Le Gall'

import getopt
import os
import sys

from xivo_ctiservers import ctiserver
from xivo_ctiservers import cti_config

try:
    cti_config.DAEMONNAME = os.path.basename(sys.argv[0])
except:
    cti_config.DAEMONNAME = 'ctid'

GETOPT_SHORTOPTS = 'dc:C:p:l:i:P:'
GETOPT_LONGOPTS = ['debug',
                   'config=',
                   'confoverride=',
                   'pidfile=',
                   'logfile=',
                   'ip=',
                   'portdelta=',
                   ]


def parse_command_line():
    for opt, arg in getopt.getopt(sys.argv[1:], GETOPT_SHORTOPTS, GETOPT_LONGOPTS)[0]:
        if opt == '-d':
            cti_config.DEBUG_MODE = True
        elif opt == '-c':
            cti_config.XIVO_CONF_FILE = arg
        elif opt == '-C':
            cti_config.XIVO_CONF_OVER = arg
        elif opt == '-p':
            cti_config.PIDFILE = arg
        elif opt == '-l':
            cti_config.LOGFILENAME = arg
        elif opt == '-i':
            cti_config.XIVOIP = arg
        elif opt == '-P':
            cti_config.PORTDELTA = int(arg)


if __name__ == '__main__':
    parse_command_line()
    if cti_config.XIVOIP != 'localhost':
        cti_config.XIVO_CONF_FILE = 'https://%s/cti/json.php/restricted/configuration' % cti_config.XIVOIP
    main = ctiserver.CTIServer()
