#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision: 4044 $
# $Date: 2008-09-12 02:48:49 +0200 (Fri, 12 Sep 2008) $

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG="pf-monit"
DEB_TB_DEPS=""

default:

