#!/bin/bash
#!/bin/sh
### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Should-Start:      fam
# Should-Stop:       fam
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start service.
### END INIT INFO

case $1 in
    start) state=0;;
    stop) state=0;;
    status) state=0;;
    *) state=1;;
esac

exit $state
