<?php

#
# XiVO Web-Interface
# Copyright (C) 2006-2011  Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

$array = array();

$array['module'] = array();

$array['module']['accesswebservice'] = array();
$array['module']['accesswebservice']['datastorage'] = true;

$array['module']['commonconf'] = array();
$array['module']['commonconf']['datastorage'] = false;

$array['module']['dahdi'] = array();
$array['module']['dahdi']['datastorage'] = false;

$array['module']['dhcp'] = array();
$array['module']['dhcp']['datastorage'] = true;

$array['module']['entity'] = array();
$array['module']['entity']['datastorage'] = true;

$array['module']['ha'] = array();
$array['module']['ha']['datastorage'] = true;

$array['module']['ha_cluster_node'] = array();
$array['module']['ha_cluster_node']['datastorage'] = true;

$array['module']['ha_service'] = array();
$array['module']['ha_service']['datastorage'] = true;

$array['module']['iproute'] = array();
$array['module']['iproute']['datastorage'] = true;

$array['module']['ldapserver'] = array();
$array['module']['ldapserver']['datastorage'] = true;

$array['module']['mail'] = array();
$array['module']['mail']['datastorage'] = true;

$array['module']['monitoring'] = array();
$array['module']['monitoring']['datastorage'] = true;

$array['module']['netiface'] = array();
$array['module']['netiface']['datastorage'] = true;

$array['module']['resolvconf'] = array();
$array['module']['resolvconf']['datastorage'] = true;

$array['module']['server'] = array();
$array['module']['server']['datastorage'] = true;

$array['module']['provisioning'] = array();
$array['module']['provisioning']['datastorage'] = true;

$array['module']['provdconfig'] = array();
$array['module']['provdconfig']['datastorage'] = false;

$array['module']['provdplugin'] = array();
$array['module']['provdplugin']['datastorage'] = false;

$array['module']['provddevice'] = array();
$array['module']['provddevice']['datastorage'] = false;

$array['module']['provdconfigure'] = array();
$array['module']['provdconfigure']['datastorage'] = false;

$array['module']['stats_conf'] = array();
$array['module']['stats_conf']['datastorage'] = true;

$array['module']['stats_conf_queue'] = array();
$array['module']['stats_conf_queue']['datastorage'] = true;

$array['module']['stats_conf_group'] = array();
$array['module']['stats_conf_group']['datastorage'] = true;

$array['module']['stats_conf_agent'] = array();
$array['module']['stats_conf_agent']['datastorage'] = true;

$array['module']['stats_conf_user'] = array();
$array['module']['stats_conf_user']['datastorage'] = true;

$array['module']['stats_conf_incall'] = array();
$array['module']['stats_conf_incall']['datastorage'] = true;

$array['module']['sysconfd'] = array();
$array['module']['sysconfd']['datastorage'] = false;

$array['module']['certificate'] = array();
$array['module']['certificate']['datastorage'] = false;

?>
